name: Test matrix + env

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  label: test

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ["foo", "bar"]
    steps:
    - name: Run a one-line script
      run: echo Value $VALUE
      env:
        VALUE: ${{ matrix.value }}
