name: Test matrix + env

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ["foo", "bar"]
    env:
      VALUE: ${{ matrix.value }}
    steps:
    - name: Run a one-line script
      run: echo Value $VALUE
